export const guiaMapeo: any = {
  modulo: 'general',
  modelo: 'guia',
  tipo: 'Administrador',
  datos: [
      {
      nombre: 'id',
      campoNombre: 'id',
      campoTipo: 'IntegerField',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: 'numero',
      campoNombre: 'Número',
      campoTipo: 'IntegerField',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: 'destinatario',
      campoNombre: 'Destinatario',
      campoTipo: 'CharField',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: 'fecha',
      campoTipo: 'DateField',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: false,
    },
    {
      nombre: 'estado_despacho',
      campoNombre: 'Despachado',
      campoTipo: 'Booleano',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: false,
    },
    {
      nombre: 'estado_decodificado',
      campoNombre: 'Decodificado',
      campoTipo: 'Booleano',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: false,
    },
    {
      nombre: 'estado_decodificado_alerta',
      campoNombre: 'Alerta',
      campoTipo: 'Booleano',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: false,
    },
    {
      nombre: 'cita_inicio',
      campoNombre: 'Cita inicio',
      campoTipo: 'DateTimeField',
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: true,
    },
    {
      nombre: 'cita_fin',
      campoNombre: 'Cita fin',
      campoTipo: 'DateTimeField',
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: true,
    },
  ],
};
