export const visitaRutearMapeo: any = {
  modulo: 'general',
  modelo: 'guia',
  tipo: 'Administrador',
  datos: [
    {
      nombre: 'numero',
      campoNombre: 'Número',
      campoTipo: 'IntegerField',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: 'franja_id',
      campoNombre: 'Franja',
      campoTipo: 'Fk',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
      esFk: true,
      busquedaAvanzada: true,
      modeloFk: 'RutFranja',
    },
    {
      nombre: 'estado_decodificado',
      campoNombre: 'Decodificado',
      campoTipo: 'Booleano',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: false,
    },
    {
      nombre: 'estado_decodificado_alerta',
      campoNombre: 'Alerta',
      campoTipo: 'Booleano',
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: false,
    },
  ],
};
