export const mapeo: any = {
  Vehiculo: {
    modulo: 'general',
    modelo: 'vehiculo',
    tipo: 'Administrador',
    datos: [
      {
        encabezado: 'ID',
        campoNombre: 'id',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Placa',
        campoNombre: 'placa',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Capacidad',
        campoNombre: 'capacidad',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: "Activo",
        campoNombre: 'estado_activo',
        campoTipo: "Boolean",
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: "Asignado",
        campoNombre: 'estado_asignado',
        campoTipo: "Boolean",
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      }
    ],
  },
  Contacto: {
    modulo: 'general',
    modelo: 'contacto',
    tipo: 'Administrador',
    datos: [
        {
          encabezado: "ID",
          campoNombre: 'id',
          campoTipo: "IntegerField",
          visibleTabla: true,
          visibleFiltro: true,
          ordenable: true,
        },
        {
          encabezado: "Tipo",
          campoNombre: 'id',
          campoTipo: "IntegerField",
          visibleTabla: true,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Identificación",
          campoTipo: "CharField",
          visibleTabla: true,
          visibleFiltro: true,
          ordenable: true,
        },
        {
          encabezado: "Digito verificación",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Nombre",
          campoTipo: "CharField",
          visibleTabla: true,
          visibleFiltro: true,
          ordenable: true,
        },
        {
          encabezado: "Correo",
          campoTipo: "CharField",
          visibleTabla: true,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Dirección",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          nombre: "Nombre1",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Nombre2",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Apellido1",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Apellido2",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Código postal",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Teléfono",
          campoTipo: "CharField",
          visibleTabla: true,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Celular",
          campoTipo: "CharField",
          visibleTabla: true,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Barrio",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Código ciuu",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Ciudad nombre",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Regimen",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
        {
          encabezado: "Tipo persona",
          campoTipo: "CharField",
          visibleTabla: false,
          visibleFiltro: false,
          ordenable: false,
        },
      ],
  }
};
