export const mapeo: any = {
  Visita: {
    modulo: 'general',
    modelo: 'visita',
    tipo: 'Documento',
    datos: [
      {
        encabezado: 'Id',
        campoNombre: 'id',
        campoTipo: 'Id',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Número',
        campoNombre: 'numero',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Fecha',
        campoNombre: 'fecha',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Documento',
        campoNombre: 'documento',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Destinatario',
        campoNombre: 'destinatario',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Dirección',
        campoNombre: 'destinatario_direccion',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Teléfono',
        campoNombre: 'destinatario_telefono',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Franja',
        campoNombre: 'franja_codigo',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Und',
        campoNombre: 'unidades',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
        tooltip: 'Unidades',
      },
      {
        encabezado: 'Peso',
        campoNombre: 'peso',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
        tooltip: 'Peso (kg)',
      },
      {
        encabezado: 'Vol',
        campoNombre: 'volumen',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
        tooltip: 'Volumen',
      },
      {
        encabezado: 'Despacho',
        campoNombre: 'despacho_id',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        // Día en que la guía salió a RUTA (fecha del despacho), distinto de
        // 'Fecha' (manifiesto/ingreso). Deja ver cuando una guía se repartió
        // otro día que su ingreso; se muestra en local por el pipe date.
        encabezado: 'Día de ruta',
        campoNombre: 'despacho__fecha',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
        tooltip: 'Día en que salió a ruta (fecha del despacho). Puede diferir de la Fecha de ingreso.',
      },
      {
        encabezado: 'Estado',
        campoNombre: 'estado_dominante',
        campoTipo: 'EstadoVisita',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
        tooltip: 'Estado dominante: Novedad > Entregado > Despachado > Pendiente',
      },
      {
        // Usuario de la app que registró la entrega (quién entregó de verdad),
        // distinto del conductor asignado al despacho. Se llena desde el token
        // móvil al entregar; guías entregadas antes de habilitarlo salen vacías.
        encabezado: 'Entregado por',
        campoNombre: 'entregado_por_nombre',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
        tooltip: 'Usuario de la app que registró la entrega.',
      },
      {
        encabezado: 'Cita inicio',
        campoNombre: 'cita_inicio',
        campoTipo: 'DateTimeField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: true,
      },
      {
        encabezado: 'Cita fin',
        campoNombre: 'cita_fin',
        campoTipo: 'DateTimeField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: true,
      },
    ],
  },
  Despacho: {
    modulo: 'general',
    modelo: 'visita',
    tipo: 'Documento',
    datos: [
      {
        encabezado: 'Id',
        campoNombre: 'id',
        campoTipo: 'Id',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Fecha',
        campoNombre: 'fecha',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Hora',
        campoNombre: 'fecha_salida',
        campoTipo: 'Hour',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Vehículo',
        campoNombre: 'vehiculo__placa',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Conductor',
        campoNombre: 'conductor_nombre',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Peso',
        campoNombre: 'peso',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Volumen',
        campoNombre: 'volumen',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Visitas',
        campoNombre: 'visitas',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Entregadas',
        campoNombre: 'visitas_entregadas',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Aprobado',
        campoNombre: 'estado_aprobado',
        campoTipo: 'Boolean',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Terminado',
        campoNombre: 'estado_terminado',
        campoTipo: 'Boolean',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
  Novedad: {
    modulo: 'general',
    modelo: 'novedad',
    tipo: 'Documento',
    datos: [
      {
        encabezado: 'Id',
        campoNombre: 'id',
        campoTipo: 'Id',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Fecha',
        campoNombre: 'fecha',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Tipo',
        campoNombre: 'novedad_tipo__nombre',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Visita',
        campoNombre: 'visita__numero',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Descripción',
        campoNombre: 'descripcion',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Solucionado',
        campoNombre: 'estado_solucion',
        campoTipo: 'Boolean',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
};
