export const mapeo: any = {
  Visita: {
    modulo: 'general',
    modelo: 'visita',
    tipo: 'Documento',
    datos: [
      {
        encabezado: 'ID',
        campoNombre: 'id',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Guia',
        campoNombre: 'guia',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Fecha',
        campoNombre: 'fecha',
        campoTipo: 'DateField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Documento',
        campoNombre: 'documento',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Destinatario',
        campoNombre: 'destinatario',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Dirección',
        campoNombre: 'destinatario_direccion',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Cod',
        campoNombre: 'ciudad_id',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Ciudad',
        campoNombre: 'ciudad_nombre',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Teléfono',
        campoNombre: 'destinatario_telefono',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Correo',
        campoNombre: 'destinatario_correo',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Pes',
        campoNombre: 'peso',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Vol',
        campoNombre: 'volumen',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Lat',
        campoNombre: 'latitud',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Lng',
        campoNombre: 'longitud',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Ord',
        campoNombre: 'orden',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Dis',
        campoNombre: 'distancia_proxima',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Cod',
        campoNombre: 'franja_id',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Franja',
        campoNombre: 'franja_nombre',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Código',
        campoNombre: 'franja_codigo',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
  Despacho: {
    modulo: 'general',
    modelo: 'visita',
    tipo: 'Documento',
    datos: [
      {
        encabezado: 'ID',
        campoNombre: 'id',
        campoTipo: 'IntegerField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Vehículo',
        campoNombre: 'vehiculo_placa',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: false,
        ordenable: false,
      },
      {
        encabezado: 'Peso',
        campoNombre: 'peso',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Volumen',
        campoNombre: 'volumen',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
      {
        encabezado: 'Visitas',
        campoNombre: 'visitas',
        campoTipo: 'CharField',
        visibleTabla: true,
        visibleFiltro: true,
        ordenable: true,
      },
    ],
  },
};
